### ISSUE TITLE
Convert document to Markdown

### ISSUE THREAD

**Issue by cachedout** [ZimboPy/Community-clubs#1]
I think that it would be easier to help edit these documents if they were written in plain text using GitHub's markdown syntax: https://guides.github.com/features/mastering-markdown/

If you like, I could start by taking the Word document and converting it to Markdown so that we could all work together on editing it more easily.

What do you think?

**Comment by ZimboPy** [comment]
Hie Mike
i really think thats a great idea and i would welcome it if you can go ahead and convert the word document to markdown.

i didn't have time to add more staff on the document because i have already started  working on the ZimboPy website.I will definately upload it here as soon i finish the basic structure.I am also wait for our new logo from our graphics designer.

**Comment by rallytime** [comment]
What if we converted the word docs to full .rst syntax instead of markdown? That way we could build out [sphinx](http://www.sphinx-doc.org/en/1.5.1/) docs later. 

I spoke with @cachedout about this today and I think that would be good to start with .rst from the get-go if these files are going to be reformatted anyway.

I can start tackling some of them in my free time.

**Comment by cachedout** [comment]
@rallytime Yes, I agree 100%. Using RestructedText is the way to go here. Then we can build everything in Sphinx and it will make it easy to print paper-bound books which can be easily distributed.

**Comment by ronnzw** [comment]
@rallytime and @cachedout i don't know much about sphinx but i have read the link that @rallytime shared,it seems good to use it. @rallytime please feel free to convert the documents.i will learn as you do it.Thank you so much

**Comment by cachedout** [comment]
@Rmaravanyika Sphinx itself can be complicated but RsT is not too hard to learn. Let me know if you have questions. :]

**Comment by ronnzw** [comment]
@cachedout what is RsT.

**Comment by cachedout** [comment]
It is just shorthand for "Restructured Text". http://docutils.sourceforge.net/rst.html

**Comment by ronnzw** [comment]
let me try to learn it.

**Comment by rallytime** [comment]
Hi @Rmaravanyika - I have converted my first document, Test Driven Development, to RestructuredText syntax in pull request #8. Perhaps you can use that as an example and starting point. 

The options that I used in this document (and use frequently in RsT) are the following:
- [Inline Markup](http://docutils.sourceforge.net/docs/user/rst/quickref.html#inline-markup) (Many of those are similar to using Markdown syntax.)
- [Section Structure](http://docutils.sourceforge.net/docs/user/rst/quickref.html#section-structure)
- [Bullet Lists](http://docutils.sourceforge.net/docs/user/rst/quickref.html#bullet-lists)
- [Enumerated Lists](http://docutils.sourceforge.net/docs/user/rst/quickref.html#enumerated-lists)
- [External Links](http://docutils.sourceforge.net/docs/user/rst/quickref.html#external-hyperlink-targets)

I also used the `.. code-block:: python` syntax to mark that the example code is a block of python code and the `.. _test-driven-development:` syntax at the top of the file, which will make internal linking to this file easy in the future using the `:ref:` syntax.

I don't know if that is helpful or not, but I thought it might be good to see what I was doing. It's not completely apparent in the pull request diff since the renaming of the file from .py to .rst changes all lines.

I am happy to answer any questions you might have about RsT as well. :)

**Comment by ZimboPy** [comment]
Hi @rallytime i have went through the stuff you have given me, RestructuredText seems to be very similar to markdown.I will create a document as rst and i will see what you think about it.Thank you so much.

**Comment by rallytime** [comment]
@ZimboPy Yes, it is very similar, which makes it easy. I think your changes look good - all of the rst syntax looks correct to me. I only had one tiny comment that I noticed. Nice work!

**Comment by drvinceknight** [comment]
I'm new here so please do let me know if my suggestion is too much on a tangent but is there any merit in writing the materials in Jupyter notebooks? 

Some examples of other things written that way:

- https://github.com/jakevdp/PythonDataScienceHandbook
- https://github.com/drvinceknight/Python-Mathematics-Handbook/tree/master/nbs

Pros:

- Exectuable;
- Tools exists to convert to any format
- Very beginner friendly

Cons: 

- You guys have already done awesome stuff going in a different direction :)

**Comment by ronnzw** [comment]
@drvinceknight i'm not very familiar with jupyter notebooks but it seems as if it writes good documentation.However as you said we are already going in one direction.Is it possible for us to reference the jupyter notebooks in the T.O.C (table of contents) that will be created using reStructuredText. If it is possible then you can go ahead and contribute using jupyter notebooks. @rallytime can i have your thoughts about this?

**Comment by drvinceknight** [comment]
I would suggest either all contributions are via Jupyter or not, mixing and matching isn't great. As you've already made such great progress using the current approach it was probably a silly suggestion of mine to begin with :) I'll follow suite with what you've already been doing :+1:
