### ISSUE TITLE
Finishing up the python sythax-with TDD

### ISSUE THREAD

**Issue by ronnzw** [ZimboPy/Community-clubs#2]
Can we get someone who can write on Test Driven development.l am not so good in that area.After this we can move on to Web development.

**Comment by cachedout** [comment]
Yes, I know just the person.

Yo, @s0undt3ch and @rallytime. You guys up for helping out with some docs for the ZimboPy folks?!

**Comment by cachedout** [comment]
OK, so @rallytime. Thanks for letting me recruit you!

Here's what we need:

As you can see, there are a number of docs present already in this repo, each of which illustrate a basic concept. We just need an additional document created which gives a student a very brief tutorial on Test Driven Development.

This could be something like a stripped down version of this (obviously redone so that copyright is not infringed): https://dzone.com/articles/tdd-python-5-minutes

Or it could could something more involved. The basic components would need to be:

1) Creating a use case
2) Writing a test to satisfy the case
3) Running the test and seeing it fail.
4) Writing a small amount of Python to ensure the case succeeds.
5) Re-running the test to see it pass.

You know where to find me with questions and thanks so much for your help! We'll get you added to a contributors list once we're that far along and thanks again!

**Comment by s0undt3ch** [comment]
So, does the above message mean @rallytime  picked up the task?

**Comment by cachedout** [comment]
@s0undt3ch Yes, she has. Thanks for your response. I'll keep you in mind for the next one. ;] You two are awesome!

**Comment by ronnzw** [comment]
@rallytime thank you so much.

**Comment by rallytime** [comment]
Certainly!

**Comment by hbutau** [comment]
@cachedout  I would be very happy to take part on the Test Driven Development part.

**Comment by cachedout** [comment]
@hbutau I think we have that covered at the moment. Any chance you could help out with some of the Python web dev curriculum?

**Comment by hbutau** [comment]
@cachedout I will help out with some django  then.

**Comment by cachedout** [comment]
@hbutau It will be issue #5 that you'll be finishing. Thank you!

**Comment by ronnzw** [comment]
@hbutau thank you so much
